### ISSUE TITLE
DotNetStarter.Structuremap should support empty constructor option

### ISSUE THREAD

**Issue by bmcdavid** [bmcdavid/DotNetStarter#3]
Currently the DotNetStarter.Structuremap ILocator only supports greediest constructors even if empty is specified in the registration.

**Comment by MiracleManS** [comment]
Here's example we had from Epi, might want to update that as well:
`        public void Add(Type serviceType, Type serviceImplementation, string key = null, LifeTime lifeTime = LifeTime.Transient, ConstructorType constructorType = ConstructorType.Greediest)
        {
            if (constructorType == ConstructorType.Greediest)
                _Container.Configure(x => x.For(serviceType).LifecycleIs(ConvertLifeTime(lifeTime)).Use(serviceImplementation));
            else
            {
                var empty = serviceImplementation.GetConstructor(Type.EmptyTypes);
                _Container.Configure(x => x.For(serviceType).LifecycleIs(ConvertLifeTime(lifeTime)).Use(serviceImplementation).Constructor = empty);
            }
        }`

**Comment by bmcdavid** [comment]
Fixed for all but the net35 Structuremap version, which functions with only greediest, also logs a not to debug for help troubleshooting.
